services:
  ztrun-backend:
    build: ./backend
    container_name: ztrun-backend
    ports:
      - "8080:8080"
    environment:
      # ... (variables existentes)
      # Esto puede ser necesario para forzar el reinicio remoto en Docker
      SPRING_DEVTOOLS_RESTART_ENABLED: true
    networks:
      - ztrun-net
    # --- CAMBIOS AQUÍ ---
    volumes:
      # Monta el código fuente
      - ./backend/src:/app/src
      # Monta el target (donde se genera el JAR)
      - ./backend/target:/app/target
      # Monta el pom.xml para que esté disponible en el contenedor
      - ./backend/pom.xml:/app/pom.xml

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - ztrun-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - ztrun-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - ztrun-net

networks:
  ztrun-net:
    driver: bridge
