services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: ztrun-postgres
    environment:
      POSTGRES_DB: ztrun_db
      POSTGRES_USER: ztrun_user
      POSTGRES_PASSWORD: ztrun_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - ztrun-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ztrun_user -d ztrun_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ztrun-backend:
  #   build: ./backend
  #   container_name: ztrun-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     # Configuración de PostgreSQL
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ztrun_db
  #     SPRING_DATASOURCE_USERNAME: ztrun_user
  #     SPRING_DATASOURCE_PASSWORD: ztrun_password
  #     SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  #     SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #     SPRING_JPA_SHOW_SQL: "true"

  #     # DevTools
  #     SPRING_DEVTOOLS_RESTART_ENABLED: "true"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     logstash:
  #       condition: service_started
  #   networks:
  #     - ztrun-net
  #   volumes:
  #     - ./backend/src:/app/src
  #     - ./backend/target:/app/target
  #     - ./backend/pom.xml:/app/pom.xml

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - ztrun-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - ztrun-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - ztrun-net

networks:
  ztrun-net:
    driver: bridge

volumes:
  postgres-data:
  elasticsearch-data:
